"""Relational schema (SQLAlchemy Core). Portable across SQLite (tests/local) and PostgreSQL."""

from __future__ import annotations

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    Column,
    Float,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
)

metadata = MetaData()

runs = Table(
    "runs",
    metadata,
    Column("run_id", String(64), primary_key=True),
    Column("name", String(128)),
    Column("mode", String(16)),
    Column("config", JSON),
    Column("config_fingerprint", String(32)),
    Column("risk_fingerprint", String(32)),
    Column("starting_capital", Float),
    Column("started_ts", BigInteger),
    Column("ends_ts", BigInteger),
    Column("ended_ts", BigInteger, nullable=True),
    Column("final_equity", Float, nullable=True),
    Column("status", String(32)),
)

genomes = Table(
    "genomes",
    metadata,
    Column("genome_id", String(32), primary_key=True),
    Column("species", String(256)),
    Column("genome", JSON),
    Column("origin", String(64)),
    Column("created_ts", BigInteger),
)

agents = Table(
    "agents",
    metadata,
    Column("run_id", String(64), primary_key=True),
    Column("agent_id", String(32), primary_key=True),
    Column("genome_id", String(32)),
    Column("species", String(256)),
    Column("generation", Integer),
    Column("parent_ids", JSON),
    Column("status", String(16)),
    Column("strikes", Integer),
    Column("born_ts", BigInteger),
    Column("died_ts", BigInteger, nullable=True),
    Column("death_reason", String(64), nullable=True),
)

lineage = Table(
    "lineage",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(64), index=True),
    Column("ts", BigInteger),
    Column("generation", Integer),
    Column("agent_id", String(32), index=True),
    Column("kind", String(16)),
    Column("genome_id", String(32)),
    Column("parent_ids", JSON),
    Column("details", JSON),
)

snapshots = Table(
    "snapshots",
    metadata,
    Column("snapshot_id", String(96), primary_key=True),
    Column("run_id", String(64), index=True),
    Column("ts", BigInteger),
    Column("symbol", String(32)),
    Column("data", JSON),
)

intents = Table(
    "intents",
    metadata,
    Column("intent_id", String(32), primary_key=True),
    Column("run_id", String(64), index=True),
    Column("ts", BigInteger),
    Column("agent_id", String(32)),
    Column("genome_id", String(32)),
    Column("symbol", String(32)),
    Column("reason", String(32)),
    Column("direction", String(8)),
    Column("target_exposure", Float),
    Column("confidence", Float),
    Column("score", Float),
    Column("regime", String(16)),
    Column("components", JSON),
    Column("features", JSON),
    Column("signals", JSON),
    Column("provider", String(64), nullable=True),
    Column("model_response", JSON, nullable=True),
    Column("snapshot_ref", String(96), nullable=True),
    Column("stop_loss_pct", Float, nullable=True),
    Column("take_profit_pct", Float, nullable=True),
    Column("max_hold_ms", BigInteger, nullable=True),
    Column("urgency", String(16)),
    Column("parent_intent_id", String(32), nullable=True),
    Index("ix_intents_agent_ts", "agent_id", "ts"),
)

risk_decisions = Table(
    "risk_decisions",
    metadata,
    Column("decision_id", String(32), primary_key=True),
    Column("run_id", String(64), index=True),
    Column("intent_id", String(32), index=True),
    Column("account_id", String(64)),
    Column("agent_id", String(32)),
    Column("symbol", String(32)),
    Column("ts", BigInteger),
    Column("approved", Boolean),
    Column("risk_increasing", Boolean),
    Column("current_qty", Float),
    Column("pending_qty", Float),
    Column("requested_qty", Float),
    Column("target_qty", Float),
    Column("order_qty", Float),
    Column("ref_price", Float, nullable=True),
    Column("agent_capital", Float),
    Column("account_equity", Float),
    Column("reasons", JSON),
    Column("clipped", Boolean),
    Column("limits_fingerprint", String(32)),
)

orders = Table(
    "orders",
    metadata,
    Column("client_order_id", String(40), primary_key=True),
    Column("run_id", String(64), index=True),
    Column("decision_id", String(32), index=True),
    Column("intent_id", String(32), index=True),
    Column("account_id", String(64)),
    Column("agent_id", String(32)),
    Column("symbol", String(32)),
    Column("side", String(8)),
    Column("qty", Float),
    Column("order_type", String(16)),
    Column("tif", String(16)),
    Column("limit_price", Float, nullable=True),
    Column("status", String(24)),
    Column("filled_qty", Float),
    Column("avg_fill_price", Float),
    Column("fees", Float),
    Column("exchange_order_id", String(64), nullable=True),
    Column("created_ts", BigInteger),
    Column("acked_ts", BigInteger, nullable=True),
    Column("last_update_ts", BigInteger),
    Column("reason", Text),
)

fills = Table(
    "fills",
    metadata,
    Column("exec_id", String(64), primary_key=True),
    Column("run_id", String(64), index=True),
    Column("client_order_id", String(40), index=True),
    Column("account_id", String(64)),
    Column("agent_id", String(32)),
    Column("symbol", String(32)),
    Column("side", String(8)),
    Column("qty", Float),
    Column("price", Float),
    Column("fee", Float),
    Column("is_maker", Boolean),
    Column("is_liquidation", Boolean),
    Column("slippage_bps", Float, nullable=True),
    Column("ts", BigInteger),
)

trades = Table(
    "trades",
    metadata,
    Column("trade_id", String(32), primary_key=True),
    Column("run_id", String(64), index=True),
    Column("account_id", String(64), index=True),
    Column("agent_id", String(32), index=True),
    Column("genome_id", String(32)),
    Column("symbol", String(32)),
    Column("direction", Integer),
    Column("entry_ts", BigInteger),
    Column("exit_ts", BigInteger),
    Column("entry_price", Float),
    Column("exit_price", Float),
    Column("max_qty", Float),
    Column("entry_notional", Float),
    Column("realized", Float),
    Column("fees", Float),
    Column("funding", Float),
    Column("net_pnl", Float),
    Column("return_on_equity", Float),
    Column("slippage_cost", Float),
    Column("mfe_pct", Float),
    Column("mae_pct", Float),
    Column("entry_confidence", Float),
    Column("entry_intent_id", String(32), nullable=True, index=True),
    Column("exit_intent_id", String(32), nullable=True, index=True),
    Column("exit_reason", String(32), nullable=True),
)

fitness = Table(
    "fitness",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(64), index=True),
    Column("generation", Integer),
    Column("ts", BigInteger),
    Column("agent_id", String(32), index=True),
    Column("fitness", Float),
    Column("adjusted_fitness", Float),
    Column("eligible", Boolean),
    Column("excess_t", Float),
    Column("max_corr", Float),
    Column("age_generations", Integer),
    Column("rank", Integer),
    Column("metrics", JSON),
)

allocations = Table(
    "allocations",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(64), index=True),
    Column("ts", BigInteger),
    Column("generation", Integer),
    Column("agent_id", String(32)),
    Column("weight", Float),
    Column("capital", Float),
    Column("allocator", String(32)),
)

equity = Table(
    "equity",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(64), index=True),
    Column("ts", BigInteger),
    Column("account_id", String(64)),
    Column("equity", Float),
    Column("cash", Float),
    Column("gross_notional", Float),
    Index("ix_equity_account_ts", "account_id", "ts"),
)

system_events = Table(
    "system_events",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(64), index=True),
    Column("ts", BigInteger),
    Column("kind", String(48)),
    Column("detail", JSON),
)

UPSERT_KEYS: dict[str, tuple[str, ...]] = {
    "agents": ("run_id", "agent_id"),
    "orders": ("client_order_id",),
    "genomes": ("genome_id",),
    "runs": ("run_id",),
}
